### ISSUE TITLE
Blank email content

### ISSUE THREAD

**Issue by ghost** [tomolimo/mailanalyzer#11]
Hello.
Your plugin is correctly associating email responses with the call.
However, it is not showing the content of the answers.
It shows that they exist, but not what they have inside them.

Help me!
GLPI 9.1.2

**Comment by tomolimo** [comment]
Hello,
Could you give content of the logs?
And also complete GLPI configuration (Setup > General > System)?
Thank you,
Tomolimo

**Comment by ghost** [comment]
Hello.
The problem was already solved.
The delimiters of header tag and footer tag were missing in the /inc/notificationtargetticket.class.php file (=-=-=-= and =_=_=_=).
Note: I deactivated the Mail Analyzer plugin and its functions remain operative. By responding to emails, the followups are automatically added to the called timeline.
It seems that version 9.1.2 of GLPI already comes native with these functions. ;)
I am sure?
Thank you.

**Comment by tomolimo** [comment]
Yes and No,
Yes when a user is responding to a GLPI notification (but was already the case in previous version), and No in any other use case.

**Comment by ghost** [comment]
What would be "other use cases"? 
Is this plugin for them?

**Comment by tomolimo** [comment]
For example:
This solves the problem of duplicated Tickets when an email is sent to GLPI and CC to others. and when those CC uses 'Reply to All', GLPI by default will create a new ticket

For that, it creates a new table in the DB with the purpose of storing email guid (generated by email clients and servers) in order to be able (if possible) to match emails in mailgate which have been sent using 'CC' and 'Reply to all'.

**Comment by mauriciotesta97** [comment]
Understood!
Thanks
:+1:

**Comment by ghost** [comment]
Understood!
Thanks
:+1:
