### ISSUE TITLE
mailanalyser doesn't work with cron method

### ISSUE THREAD

**Issue by Skouat** [tomolimo/mailanalyzer#28]
Hi @tomolimo,

Since my previous PR (https://github.com/tomolimo/mailanalyzer/pull/27) mailanalyser works only if I execute the mailgate via "Automatic actions".
If I setup the "Run mode" to cron, all emails are imported as new tickets instead of added to the corresponding ticket.

Any ideas ?

**Comment by tomolimo** [comment]
Hello @Skouat 
Could you remind me the version of GLPI you are using?
Thank you
Regards,
Tomolimo

**Comment by Skouat** [comment]
I'm using GLPI 9.4.x

**Comment by tomolimo** [comment]
Hello @Skouat 
Could you check if there are logs in the php-errors.log files?
Thank you
Regards,
Tomolimo

**Comment by Skouat** [comment]
Hi @tomolimo,

In my previous reply, I indicated a wrong version of GLPI. I've updated my previous comment.

There is no logs in the php-errors.logs file.

Please find, below some feedbacks:
  * When I set mailgate to GLPI and run it manually, it works.
  * When I set mailgate to CLI and run it manually, it doesn't do the job.

**Comment by tomolimo** [comment]
Hello @Skouat 
In order to be able to help you, I need to have more information.
Which version of plugin do you use?
What are the steps to reproduce this behavior? I made tests with GLPI 9.4 and was not able to reproduce. So you may have something in your configuration or in the emails that I don't have. Could you detail as much as possible the steps to reproduce the issue?
Thank you,
Regards,
Tomolimo

**Comment by Skouat** [comment]
Hi,

Now, It seems working. I'll monitor all tickets.
I let you know.

**Comment by Skouat** [comment]
It really works again. I close this ticket.

Thanks for your time.
