### ISSUE TITLE
9.5.3 - ##from no longer exists. Is it normal?

### ISSUE THREAD

**Issue by andrepetinga** [tomolimo/mailanalyzer#44]
Hello.
I've tested the new version of the plugin in 9.5.3 and for the prevention of duplicates is working fine.
But I noticed that the ##from no longer works :(

Is it normal??

**Comment by tomolimo** [comment]
Hello @andrepetinga 
Yes, that's normal: I've planned to move this feature from **mailanalyzer** into a new plugin.
In order to group into this new plugin features like ##From ##CC, and so on. And to have a dedicated a decent wiki to give plenty of details about these.
This new plugin will be called **mailbehaviours** will come very quick, probably this week.
Thank you
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
Hello.
Uau, great! 👍

**Comment by tomolimo** [comment]
Hello @andrepetinga 
You may check the new plugin here https://github.com/tomolimo/mailbehaviours
Thank you
Regards,
Tomolimo

**Comment by andrepetinga** [comment]
Hello.
Just installed it today and already opened an issue... Sorry...
