### ISSUE TITLE
Ticketloss / Dataloss

### ISSUE THREAD

**Issue by blippercop** [tomolimo/mailanalyzer#64]
GLPI 9.5.7
Plugin 2.0.2

We had a mail that seem to be gone even while in ACCEPTED folder.
Investigation showed that when the plugin is disabled it imports it fine.
Further investigation revealed that the "message-id" of the mail was already existing in the "imported mails" list in the database.
So it was a message id collision??
However the ticked id (from the table with the imported mails) that was associated with the mail was dated for 2019 and when I tried to open the ticket it said "ticket does not exists".

So either:
- The ticket was deleted while importing the new mail??
or:
 - The new mail was simply not imported because it thought it was already imported

However that should not be the case if the ticket does not exists anymore or is closed for a that long time.
The person did definitely did not reply or something from the original message. The person was not even working in 2019.

Other question: How is the behaviour if the ticket is closed for a long time? I don't know.

Suggestion: Better validation that the new message is definitely imported or alternatively a config settings for how log the plugin merges tickets (ex. only last 30 days + database is cleaned up).

**Comment by tomolimo** [comment]
Hello @blippercop,

The plugin doesn't delete any ticket...
And it will not import a new email when the message-id is alerady existing in the table.
But it will not delete the message-id when a ticket is deleted, that's can be the root cause of the issue: I'm going to provide you with a new version of the plugin that will delete the message-id when a ticket is deleted (=purged).

Thank you,
Regards,
Tomolimo
