### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by felipepimentel08** [tomolimo/mailanalyzer#80]
Hello, Tomolino, how are you?

Just a suggestion.

Would it be possible to treat the email message to bring only the latest reply without the signature and previous content from the email body?

This would make the follow-up cleaner.

Cheers and thank you for continuing to share this plugin with the community.

**Comment by tomolimo** [comment]
Hello @felipepimentel08 
This is generally not possible, due to the email protocol that doesn't clearly give hints to split the original email with the answers.
BUT, GLPI provide such mechanism sending in the original notification two tags that are used to clean the recieved answer.
BUT, there is also a plugin ([ticketcleaner](https://github.com/tomolimo/ticketcleaner)) that you may use to clean the followups.
But this is clearly not the purpose of this plugin.
Thank you,
regards,
Tomolimo
